### ISSUE TITLE
Обработка аватарок

### ISSUE THREAD

**Issue by IgorDuino** [PROCOLLAB-github/api#152]
При загрузке аватарки создание задачи, которая сжимает аватарку до 500x500, конвертирует в webpk

<img src="https://uploads.linear.app/c3081d71-5706-4804-9b32-940b39eda6fd/da23e369-ac65-4e45-9718-1e113df1af6b/f0543e2b-683d-4f8f-be6b-b0f3e0bbaf18?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2MzMDgxZDcxLTU3MDYtNDgwNC05YjMyLTk0MGIzOWVkYTZmZC9kYTIzZTM2OS1hYzY1LTRlNDUtOTcxOC0xZTExM2RmMWFmNmIvZjA1NDNlMmItNjgzZC00ZjhmLWJlNmItYjBmM2UwYmJhZjE4IiwiaWF0IjoxNzE5ODM5MzEzLCJleHAiOjMzMjkwMzk5MzEzfQ.yk5VASPvJGdI4WhX1CLzIoWwoMXJRvzjB8ywZW93w7A " alt="image.png" width="510" height="579" />

**Comment by Yakser** [comment]
обязательно пофиксим, спасибо за пользование нашей невероятной платформой❤️😂

**Comment by VeryBigSad** [comment]
обязательно пофиксим (не факт) (for legal reasons, this is a joke)
